#' Calculates overall course grade
#' 
#' @param courseDF Course data frame generated by uploadAssignments().
#' @param courseCategoryDF Category data frame generated by createCourseWeights().
#' @returns Overall course grade.
#' @examples
#' calcGrade(PSY2012, PSY2012Categories)

calcGrade <- function(courseDF, courseCategoryDF) {
  
  courseDF$AssignmentGrade <- as.numeric(courseDF$AssignmentGrade)
  
  groupedDF <- courseDF %>% group_by(CategoryName)
  
  groupedDF <- groupedDF %>% summarise(
    AssignmentGrade = mean(AssignmentGrade),
    )
  
  groupedDF <- merge(groupedDF, courseCategoryDF)
  
  totalGrade <- 0
  
  for (x in 1:nrow(groupedDF)) {
    grade <- groupedDF$AssignmentGrade[x] * groupedDF$CategoryWeight[x]
    totalGrade <- totalGrade + grade
  }
  
  round(totalGrade, 2)
  
}



